DIST_TARGET_PATH := $(IMAGE)/system/development/headers

all:

deps:

install:
	@cp -rp * $(DIST_TARGET_PATH)/
	rm -rf $(DIST_TARGET_PATH)/CVS
	rm $(DIST_TARGET_PATH)/Makefile
# TODO: Create syllable -> atheos symlink

doc:

install-doc:

dist: install

clean:
